Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine38"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Docker"
  end

  config.vm.network "private_network", ip: "192.168.50.4"

  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 9987, host: 9987
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.network "forwarded_port", guest: 5000, host: 5000
 
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "./src/", "/mnt/docker"
  
  config.vm.provision :shell, run: "once", path: "./config/create.sh"
  config.vm.provision :shell, run: "always", path: "./config/start.sh"    
end
